"""initial schema

Every table in architecture.md §4, plus the first-boot rows in ``settings``.

The seed values are written out literally rather than imported from
``arc.models.settings.DEFAULT_SETTINGS``: a migration is a historical record
and must keep applying the same way after the application's defaults move on.
Both lists are kept in step by ``tests/test_migrations.py``.

Revision ID: 1f8e6e03fdf6
Revises:
Create Date: 2026-09-05 21:08:11.099330

"""
import json
from typing import Any, Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f8e6e03fdf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Admin-editable acquisition/retention rules (spec FR-A1, FR-A3, FR-T1,
# FR-T2, FR-T5). Mirrors arc.models.settings.DEFAULT_SETTINGS.
SEED_SETTINGS: dict[str, Any] = {
    "preferred_groups": [],
    "preferred_resolution": "1080p",
    "fallback_resolution": "720p",
    "look_ahead_n": 2,
    "grace_days_g": 7,
    "unwatched_days_d": 21,
    "sub_lang": "en",
    "audio_lang": "ja",
}


def _sql_string(value: str) -> str:
    """``value`` as a single-quoted SQL string literal."""
    return "'" + value.replace("'", "''") + "'"


def _seed_settings_sql() -> str:
    """The seed INSERT, rendered as literal SQL.

    Literal SQL rather than ``op.execute(postgresql.insert(...).values(...))``
    on purpose: a Core insert with bound parameters cannot be rendered by
    ``alembic upgrade --sql`` (offline mode), and this migration has to be
    reviewable as plain SQL before it is run against production.

    ``ON CONFLICT DO NOTHING`` so that re-running this on a database that
    already has an admin's edited values leaves them alone.
    """
    rows = ", ".join(
        f"({_sql_string(key)}, {_sql_string(json.dumps(value))}::jsonb)"
        for key, value in SEED_SETTINGS.items()
    )
    return f"INSERT INTO settings (key, value) VALUES {rows} ON CONFLICT (key) DO NOTHING"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('title_romaji', sa.Text(), nullable=True),
    sa.Column('title_english', sa.Text(), nullable=True),
    sa.Column('title_native', sa.Text(), nullable=True),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('season', sa.String(length=16), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('studio', sa.Text(), nullable=True),
    sa.Column('relations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_airing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anime'))
    )
    op.create_index(op.f('ix_anime_mal_id'), 'anime', ['mal_id'], unique=False)
    op.create_index('ix_anime_status', 'anime', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=32), server_default='pending', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_status_run_after_priority', 'jobs', ['status', 'run_after', 'priority'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole', native_enum=False, length=32), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    # Case-insensitive uniqueness: a functional index, because a plain UNIQUE
    # on the column would admit both 'bob@x.com' and 'Bob@x.com'.
    op.create_index('uq_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_table('episodes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('air_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('not_wanted', 'wanted', 'searching', 'downloading', 'downloaded', 'matching', 'matched', 'preparing', 'ready', 'failed', 'unavailable', name='episodestate', native_enum=False, length=32), server_default='not_wanted', nullable=False),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('unavailable_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], name=op.f('fk_episodes_anime_id_anime'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes')),
    sa.UniqueConstraint('anime_id', 'number', name='uq_episodes_anime_id_number')
    )
    op.create_index('ix_episodes_air_at', 'episodes', ['air_at'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_invites_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invites_token_hash'))
    )
    op.create_table('list_entries',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('watching', 'planned', 'on_hold', 'dropped', 'completed', name='liststatus', native_enum=False, length=32), nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Enum('arc', 'mal', name='updatedby', native_enum=False, length=32), server_default='arc', nullable=False),
    sa.Column('mal_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mal_dirty', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], name=op.f('fk_list_entries_anime_id_anime'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_list_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'anime_id', name=op.f('pk_list_entries'))
    )
    op.create_table('mal_links',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mal_username', sa.String(length=64), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_import_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mal_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_mal_links'))
    )
    op.create_table('mal_write_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cause', sa.Enum('watch', 'manual', 'revert', name='malwritecause', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ok', 'failed', name='malwritestatus', native_enum=False, length=32), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], name=op.f('fk_mal_write_log_anime_id_anime'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mal_write_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mal_write_log'))
    )
    op.create_index('ix_mal_write_log_user_id_created_at', 'mal_write_log', ['user_id', 'created_at'], unique=False)
    op.create_table('rec_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('picks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rec_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rec_runs'))
    )
    op.create_index('ix_rec_runs_user_id_created_at', 'rec_runs', ['user_id', 'created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('media_files',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('episode_id', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_state', sa.Enum('auto', 'pending', 'confirmed', 'ignored', name='reviewstate', native_enum=False, length=32), server_default='auto', nullable=False),
    sa.Column('llm_suggestion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_media_files_episode_id_episodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files')),
    sa.UniqueConstraint('path', name=op.f('uq_media_files_path'))
    )
    op.create_index('ix_media_files_episode_id', 'media_files', ['episode_id'], unique=False)
    op.create_index('ix_media_files_review_state', 'media_files', ['review_state'], unique=False)
    op.create_table('renditions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('episode_id', sa.BigInteger(), nullable=False),
    sa.Column('dir', sa.Text(), nullable=False),
    sa.Column('playlist_path', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('subtitle_lang', sa.String(length=16), nullable=True),
    sa.Column('audio_lang', sa.String(length=16), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_renditions_episode_id_episodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_renditions')),
    sa.UniqueConstraint('episode_id', name=op.f('uq_renditions_episode_id'))
    )
    op.create_table('torrents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('episode_id', sa.BigInteger(), nullable=False),
    sa.Column('info_hash', sa.String(length=64), nullable=False),
    sa.Column('magnet', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('seeders', sa.Integer(), nullable=True),
    sa.Column('trusted', sa.Boolean(), nullable=True),
    sa.Column('qbit_state', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_torrents_episode_id_episodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_torrents')),
    sa.UniqueConstraint('info_hash', name=op.f('uq_torrents_info_hash'))
    )
    op.create_index('ix_torrents_episode_id', 'torrents', ['episode_id'], unique=False)
    op.create_table('wants',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('episode_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dropped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drop_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_wants_episode_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'episode_id', name=op.f('pk_wants'))
    )
    op.create_index('ix_wants_episode_id_active', 'wants', ['episode_id'], unique=False, postgresql_where=sa.text('dropped_at IS NULL'))
    op.create_table('watch_progress',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('episode_id', sa.BigInteger(), nullable=False),
    sa.Column('position_s', sa.Float(), server_default='0', nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_watch_progress_episode_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watch_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'episode_id', name=op.f('pk_watch_progress'))
    )
    op.create_index('ix_watch_progress_user_id_updated_at', 'watch_progress', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###

    op.execute(_seed_settings_sql())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watch_progress_user_id_updated_at', table_name='watch_progress')
    op.drop_table('watch_progress')
    op.drop_index('ix_wants_episode_id_active', table_name='wants', postgresql_where=sa.text('dropped_at IS NULL'))
    op.drop_table('wants')
    op.drop_index('ix_torrents_episode_id', table_name='torrents')
    op.drop_table('torrents')
    op.drop_table('renditions')
    op.drop_index('ix_media_files_review_state', table_name='media_files')
    op.drop_index('ix_media_files_episode_id', table_name='media_files')
    op.drop_table('media_files')
    op.drop_table('sessions')
    op.drop_index('ix_rec_runs_user_id_created_at', table_name='rec_runs')
    op.drop_table('rec_runs')
    op.drop_index('ix_mal_write_log_user_id_created_at', table_name='mal_write_log')
    op.drop_table('mal_write_log')
    op.drop_table('mal_links')
    op.drop_table('list_entries')
    op.drop_table('invites')
    op.drop_index('ix_episodes_air_at', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index('ix_jobs_status_run_after_priority', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_anime_status', table_name='anime')
    op.drop_index(op.f('ix_anime_mal_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
