"""watch_progress unmarked_at

When the user last took a watched mark back (FR-S4's explicit un-mark),
nullable and never moved backwards. It is what lets a completion recorded
offline and replayed later (FR-S8, ``POST /api/sync``) be judged ``stale``
against an un-mark the user made *after* it, elsewhere: without it, an offline
rewatch could re-complete an episode and re-raise the list over a later
explicit un-mark (owner, 2026-10-05). Null on every existing row, which is the
truthful value — no un-mark has been recorded with a time yet.

Reviewed by hand: one nullable column, no default, no backfill, no index (it is
only ever read by primary key, under the row lock the sync takes).

Revision ID: 4e76a09e547c
Revises: d81f4b6ca3e7
Create Date: 2026-10-05 01:40:47.240461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e76a09e547c'
down_revision: Union[str, Sequence[str], None] = 'd81f4b6ca3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_progress', sa.Column('unmarked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_progress', 'unmarked_at')
    # ### end Alembic commands ###
