"""index sessions.expires_at

Autogenerated, then reviewed. Every other query against ``sessions`` is an
equality on the primary key, so the table had no other index. The hourly purge
in ``arc.worker`` is the exception — ``DELETE FROM sessions WHERE expires_at <=
now()`` — and without this it is a sequential scan over every live session,
once an hour, forever.

Not unique, and deliberately not partial: expiries are spread out and the
planner wants a plain btree range scan.

Revision ID: db097fe20f06
Revises: 28c2f8e23ce2
Create Date: 2026-09-05 19:46:12.003528

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db097fe20f06"
down_revision: str | Sequence[str] | None = "28c2f8e23ce2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_index("ix_sessions_expires_at", "sessions", ["expires_at"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_sessions_expires_at", table_name="sessions")
