"""m15.5 offline catalogue tables

The three tables the weekly offline import writes (M15.5, architecture.md §4,
§5.0a): ``offline_anime`` from manami's ``anime-offline-database``,
``offline_ids`` from Fribb's ``anime-lists``, and ``offline_imports``, the
one-row-per-source log of which release is loaded and when.

Autogenerated and then hand-edited in one place: ``CREATE EXTENSION IF NOT
EXISTS pg_trgm`` in front of the trigram index. ``ix_offline_anime_search_trgm``
is a GIN index with ``gin_trgm_ops``, which is what lets the later search task
run ``search_text ILIKE '%needle%'`` against 41k rows without a sequential
scan — and the operator class does not exist until the extension does. The
official ``postgres:18`` image ships pg_trgm, and the deployment's database
user owns its database, so the ``CREATE`` succeeds where it runs at all.

The downgrade deliberately does **not** drop the extension. Dropping something
another table's index might depend on is not a reversal, it is a different
migration; ``pg_trgm`` costs nothing to leave behind.

No foreign keys in either direction: these tables are a cache of a public
file, replaced whole by the import and owned by nothing in Arc's own model.

Revision ID: a5f4ae93df3d
Revises: 276167cbca27
Create Date: 2026-09-12 01:05:46.653333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5f4ae93df3d'
down_revision: Union[str, Sequence[str], None] = '276167cbca27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-added: ``gin_trgm_ops`` below needs it, and it must exist before
    # the index that uses it is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('offline_anime',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('kitsu_id', sa.Integer(), nullable=True),
    sa.Column('anidb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('season', sa.String(length=16), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('studios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('related', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offline_anime'))
    )
    op.create_index(op.f('ix_offline_anime_anilist_id'), 'offline_anime', ['anilist_id'], unique=False)
    op.create_index(op.f('ix_offline_anime_mal_id'), 'offline_anime', ['mal_id'], unique=False)
    op.create_index('ix_offline_anime_search_trgm', 'offline_anime', ['search_text'], unique=False, postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.create_index('ix_offline_anime_season', 'offline_anime', ['season_year', 'season'], unique=False)
    op.create_table('offline_ids',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('anidb_id', sa.Integer(), nullable=True),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('kitsu_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_tv_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_movie_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_season', sa.Integer(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_season', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offline_ids'))
    )
    op.create_index(op.f('ix_offline_ids_anilist_id'), 'offline_ids', ['anilist_id'], unique=False)
    op.create_index(op.f('ix_offline_ids_mal_id'), 'offline_ids', ['mal_id'], unique=False)
    op.create_table('offline_imports',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source', name=op.f('pk_offline_imports'))
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('offline_imports')
    op.drop_index(op.f('ix_offline_ids_mal_id'), table_name='offline_ids')
    op.drop_index(op.f('ix_offline_ids_anilist_id'), table_name='offline_ids')
    op.drop_table('offline_ids')
    op.drop_index('ix_offline_anime_season', table_name='offline_anime')
    op.drop_index('ix_offline_anime_search_trgm', table_name='offline_anime', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_offline_anime_mal_id'), table_name='offline_anime')
    op.drop_index(op.f('ix_offline_anime_anilist_id'), table_name='offline_anime')
    op.drop_table('offline_anime')
    # pg_trgm is left installed on purpose; see the module docstring.
