"""add invites.created_at

Autogenerated, then reviewed. The M2 admin invite listing shows when each
invite was issued alongside who issued it (``created_by``), which the initial
schema had no column for. Backfilled by the server default, so existing rows
read as "created at migration time" rather than NULL — there were no invites
before M2 anyway, since nothing could create one.

Revision ID: 28c2f8e23ce2
Revises: 1f8e6e03fdf6
Create Date: 2026-09-05 19:13:17.122020

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28c2f8e23ce2"
down_revision: str | Sequence[str] | None = "1f8e6e03fdf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "invites",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("invites", "created_at")
