"""Column shorthands shared by the model modules.

These exist so the same decision (what a primary key is, what a timestamp
looks like) is written once. They are plain factories, not mixins: every call
must produce a *new* ``MappedColumn``, because a single instance cannot be
attached to two tables.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Identity, func
from sqlalchemy.orm import MappedColumn, mapped_column

#: Every point-in-time column in Arc is timezone-aware; the application works
#: in UTC and renders in the user's timezone.
TZDateTime = DateTime(timezone=True)


def bigint_pk() -> MappedColumn[int]:
    """``BIGINT GENERATED BY DEFAULT AS IDENTITY`` surrogate key."""
    return mapped_column(BigInteger, Identity(always=False), primary_key=True)


def created_at() -> MappedColumn[datetime]:
    """Row creation time, defaulted by the database."""
    return mapped_column(TZDateTime, nullable=False, server_default=func.now())


def updated_at() -> MappedColumn[datetime]:
    """Last-change time, maintained by the ORM on every flush.

    ``onupdate`` is Python-side rather than a trigger: the only writer is the
    application, and a trigger would be invisible to anyone reading the
    models.

    The cost of that choice: ``onupdate`` fires only for ORM/Core ``UPDATE``
    statements. It does **not** fire for the ``DO UPDATE`` half of
    ``insert().on_conflict_do_update()``, so every upsert must set the column
    itself — ``set_={..., "updated_at": func.now()}`` — or the row will keep
    the timestamp of the insert that first created it.
    """
    return mapped_column(
        TZDateTime,
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
